---
title: "eusilc_varnames"
author: "Markus Kainu"
date: "26.05.2014"
output:
  html_document:
    theme: united
    toc: yes
---

```{r global_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.width=12, fig.height=8, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE, eval=TRUE, results='asis')
```


# Longitudinal

## Personal register




```{r}
library(r.eusilc)
path.longi.2010 <- "~/data/demo_data/eusilc_subset/2010/longi_rev2/"
#
tbl <- check_variables(file = "personal_register",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```


## Personal data

```{r}
tbl <- check_variables(file = "personal_data",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```

## Household register

```{r}
tbl <- check_variables(file = "household_register",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```

## Household data

```{r}
tbl <- check_variables(file = "household_data",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```


# cross-sectional data

Personal register

```{r}
library(r.eusilc)
path.longi.2010 <- "~/data/demo_data/eusilc_subset/2010/cross_rev3/"
#
tbl <- check_variables(file = "personal_register",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```


## Personal data

```{r}
tbl <- check_variables(file = "personal_data",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```

## Household register

```{r}
tbl <- check_variables(file = "household_register",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```

## Household data

```{r}
tbl <- check_variables(file = "household_data",
                origin.path = path.longi.2010)
tbl$Z <- "Z"
names(tbl) <- c("varname","Z")
kable(tbl)
```

